# configs/logger/aim.yaml
_target_: lightning.pytorch.loggers.AimLogger

experiment: "Spatial-CLIP-Experiments" # Aim UI 中显示的项目名称
name: ${name} # 每个运行的名称，将从主配置中动态传入
repo: ${paths.log_dir}/aim # Aim 数据库的存储位置